---
asn: 65102
loopback_ip: 10.255.0.12

underlay_interfaces:
  - name: swp1
    peer: spine01
    ip: 10.0.0.5/31
    peer_ip: 10.0.0.4

  - name: swp2
    peer: spine02
    ip: 10.0.0.7/31
    peer_ip: 10.0.0.6
