---
asn: 65101
loopback_ip: 10.255.0.11

underlay_interfaces:
  - name: swp1
    peer: spine01
    ip: 10.0.0.1/31
    peer_ip: 10.0.0.0

  - name: swp2
    peer: spine02
    ip: 10.0.0.3/31
    peer_ip: 10.0.0.2
