---
all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"

    leafs:
      hosts:
        leaf01:
        leaf02:

    spines:
      hosts:
        spine01:
        spine02:

    test_hosts:
      hosts:
        host01:
        host02:
