---
all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"

    leafs:
      hosts:
        leaf01:
          ansible_host: 10.10.10.11
        leaf02:
          ansible_host: 10.10.10.12

    spines:
      hosts:
        spine01:
          ansible_host: 10.10.10.21
        spine02:
          ansible_host: 10.10.10.22
